- name: download new parity binary
  get_url:
    url: "{{ parity_deb_url }}"
    dest: "{{base_dir}}/parity.deb"
    force: yes
  tags: update

- name: install parity
  shell: dpkg -i "{{base_dir}}/parity.deb"
  become: yes
  tags: update

- name: copy parity run-script
  template: src=run-parity.sh dest="{{base_dir}}/run-parity.sh"
  notify: restart pm2
  tags:
    - update
    - restart

- name: open parity ports
  ufw: rule=allow port=30303 proto={{ item }}
  notify: reload ufw
  with_items:
    - tcp
    - udp
  when: enable_ufw
  
- name: get enodes
  uri:
    url: http://localhost:8545
    method: POST
    body: {
      jsonrpc: "2.0",
      method: "parity_enode",
      id: 1
    }
    body_format: json
  register: enode
  tags:
    - update
    - get-enode

- debug:
    var: enode.json.result
  tags:
    - update
    - get-enode
    
