---
- name: install nginx
  apt: name=nginx state=present

- name: Copy nginx configuration for server
  template: src=nginx.conf dest=/etc/nginx/nginx.conf
  notify:
  - restart nginx
  
- name: start nginx
  sudo: yes
  service: name=nginx state=started enabled=true

- name: open HTTP port
  ufw: rule=allow port=80 proto=tcp
  notify: reload ufw

- name: open HTTPS port
  ufw: rule=allow port=443 proto=tcp
  notify: reload ufw
