---
- name: restart nginx
  sudo: yes
  service: name=nginx state=restarted

- name: reload nginx
  sudo: yes
  service: name=nginx state=reloaded

- name: reload ufw
  sudo: yes
  ufw: state=reloaded
