- name: download new parity binary
  get_url:
    url: "{{ parity_deb_url }}"
    dest: "{{base_dir}}/parity.deb"
    force: yes
  tags: update

- name: install parity
  shell: dpkg -i "{{base_dir}}/parity.deb"
  become: yes
  tags: update
