- name: update software
  apt: update_cache=yes 

- name: install prereqs
  apt: state=present pkg={{ item }}
  with_items:
    - git
    - build-essential
    - python-software-properties
    - python-dev
    - python-pip
    - curl
    - ufw

- name: firewall default deny
  ufw: state=disabled policy=deny
  when: enable_ufw

- name: open the ssh port
  ufw: rule=allow port=22 proto=tcp state=enabled
  when: enable_ufw


