mongodb_config_path: "{{base_dir}}/mongo.conf"
mongodb_config_path_docker: /etc/mongo.conf
mongo_admin_user: admin
mongo_admin_pass: "{{lookup('password', 'credentials/' + mongo_admin_user + ' length=20 chars=ascii_letters,digits')}}"
